import { LegalPage } from './LegalPage';

export function Terms() {
  return (
    <LegalPage
      title="Terms & Conditions"
      effectiveDate="May 28, 2026"
      lastUpdated="May 28, 2026"
    >
      <h2>Welcome to LivePsalms</h2>

      <p>
        These Terms and Conditions (these "Terms") constitute a legally binding contract between you
        ("you," "your," or "User") and LivePsalms ("LivePsalms," "we," "us," or "our") governing
        your access to and use of the LivePsalms website, mobile applications, application
        programming interfaces (APIs), and all associated software, features, products, and services
        (collectively, the "Services").
      </p>

      <p>
        By creating an account, accessing, or using any part of the Services, you accept and agree
        to be bound by these Terms and our Privacy Policy, which is incorporated herein by
        reference. If you do not agree to these Terms or the Privacy Policy, you must not access or
        use our Services.
      </p>

      <p>
        If you are using the Services on behalf of a church, non-profit ministry, business, or other
        legal entity, you represent and warrant that you have the legal authority to bind that entity
        to these Terms. In such cases, "you" and "your" will refer to that entity.
      </p>

      <hr />

      <h2>1. Description of Services and No-Advice Disclaimer</h2>

      <p>
        LivePsalms provides an interactive, faith-based note-taking platform designed to support
        Christian devotional practices, sermon note organization, and thematic Bible study. Key
        features include rich-text editors, custom folder structures, a visual graph representation
        of interconnected notes, and our optional AI-powered assistant, "Lamplight."
      </p>

      <h3>Spiritual and Counseling Disclaimer</h3>

      <p>
        The Services, including any Bible translations, theological reference materials, study
        guides, and content generated by our Lamplight AI features (collectively, "Service
        Materials"), are provided solely for educational, informational, and personal devotional
        purposes.
      </p>

      <blockquote>
        <p>
          <strong>Important Notice</strong>: LivePsalms does not provide professional pastoral
          counseling, mental health therapy, legal counsel, or financial advice. The spiritual
          insights, connection cards, and daily devotions generated by our AI features are
          probabilistic, machine-generated suggestions and should not be treated as authoritative
          theological guidance or professional counseling. You are solely responsible for
          evaluating, verifying, and applying any insights or recommendations obtained through our
          Services. Always consult with qualified professionals or trusted spiritual leaders for
          specific pastoral or personal counseling needs.
        </p>
      </blockquote>

      <hr />

      <h2>2. Eligibility and Account Registration</h2>

      <h3>2.1 Age Requirements and Parental Consent</h3>

      <p>
        You must be at least 13 years old to access or use the Services (or at least 16 years old
        in certain jurisdictions, including the European Union, where local laws establish a higher
        age of digital consent) [1]. If you are under the age of majority in your jurisdiction but
        at least 13 (or 16) years old, you may only use the Services under the supervision of a
        parent or legal guardian who agrees to be bound by these Terms. By using the Services, you
        represent and warrant that you meet these eligibility requirements.
      </p>

      <h3>2.2 Account Creation and Security</h3>

      <p>
        To access certain features of the Services, including cloud synchronization and our
        Lamplight AI suite, you must register for an account. When registering, you agree to:
      </p>

      <ul>
        <li>Provide accurate, current, and complete registration information.</li>
        <li>
          Maintain and promptly update your account information to keep it accurate, current, and
          complete.
        </li>
        <li>
          Maintain the strict confidentiality of your account credentials, including your password.
        </li>
        <li>
          Accept sole responsibility for all activities, actions, and charges that occur under your
          account.
        </li>
        <li>
          Notify us immediately at{' '}
          <a href="mailto:support@livepsalms.com">support@livepsalms.com</a> of any unauthorized
          use of your account or any other breach of security.
        </li>
      </ul>

      <p>
        We reserve the right to suspend or terminate your account if we have reasonable grounds to
        suspect that any information you provided is inaccurate, false, or misleading.
      </p>

      <hr />

      <h2>3. Subscription Plans, Fees, and Billing</h2>

      <p>
        LivePsalms offers both free and paid subscription tiers. By subscribing to a paid plan, you
        agree to the pricing, billing, and payment terms set forth at the time of purchase.
      </p>

      <h3>3.1 Subscription Tiers and Pricing</h3>

      <p>
        The specific features, storage limits, and AI processing quotas associated with each
        subscription tier are detailed on our pricing page and are summarized below:
      </p>

      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Subscription Tier</th>
              <th>Billing Cycle</th>
              <th>Key Features Included</th>
              <th>Payment Method</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Free Tier</strong></td>
              <td>N/A</td>
              <td>Basic rich-text note-taking, local browser storage, manual export.</td>
              <td>None required</td>
            </tr>
            <tr>
              <td><strong>Lite Tier</strong></td>
              <td>Monthly or Annual</td>
              <td>
                Secure cloud sync, folder structures, basic visual graph, limited Lamplight AI
                credits.
              </td>
              <td>Credit/Debit Card</td>
            </tr>
            <tr>
              <td><strong>Plus Tier</strong></td>
              <td>Monthly or Annual</td>
              <td>
                Secure cloud sync, unlimited visual graph, priority Lamplight AI processing,
                advanced insights.
              </td>
              <td>Credit/Debit Card</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h3>3.2 Automatic Renewal</h3>

      <p>
        All paid subscriptions are billed in advance on a recurring basis (monthly or annually,
        depending on your selection) and will <strong>automatically renew</strong> at the end of
        each billing cycle under the same terms unless you cancel your subscription or we terminate
        it. You must cancel your subscription at least 24 hours before your renewal date to prevent
        the next cycle's fees from being charged to your payment method.
      </p>

      <h3>3.3 Cancellation and Refunds</h3>

      <p>
        You can cancel your subscription at any time through your Profile settings. Upon
        cancellation, you will continue to have access to the paid features of your subscription
        until the end of your current billing cycle.
      </p>

      <p>
        All fees paid are <strong>non-refundable</strong> except:
      </p>

      <ul>
        <li>As explicitly required by applicable local consumer protection laws.</li>
        <li>
          In the event of a material service disruption where we fail to provide access to the
          Services for an extended period, in which case we may issue a prorated credit or refund at
          our sole discretion.
        </li>
      </ul>

      <h3>3.4 Price Modifications</h3>

      <p>
        We reserve the right to adjust our subscription fees and pricing structures at any time. We
        will provide you with at least 30 days' advance notice of any price changes via email or a
        prominent notification within the application. Any price adjustment will take effect only at
        the start of your next billing cycle following the notice period. If you do not agree to the
        price adjustment, your sole remedy is to cancel your subscription prior to the renewal date.
      </p>

      <hr />

      <h2>4. User-Generated Content and Intellectual Property</h2>

      <p>
        LivePsalms allows you to create, upload, store, and organize notes, folders, tags, and other
        materials (collectively, "User Content").
      </p>

      <h3>4.1 Ownership of User Content</h3>

      <p>
        <strong>
          You retain complete ownership of all intellectual property rights in your User Content.
        </strong>{' '}
        LivePsalms does not claim any ownership, copyright, or proprietary rights over the notes,
        folders, or tags you create. Your spiritual reflections, prayers, and personal study
        materials remain yours alone.
      </p>

      <h3>4.2 License Grant to LivePsalms</h3>

      <p>
        To provide the Services, we require a limited legal license to process your User Content. By
        uploading, submitting, or creating User Content on our platform, you grant LivePsalms a
        worldwide, non-exclusive, royalty-free, fully paid-up, sublicensable (solely to our
        sub-processors as detailed in our Privacy Policy), and transferable license to host, store,
        reproduce, modify, transmit, and display your User Content{' '}
        <strong>
          solely as necessary to deliver, maintain, secure, and improve the Services for you
        </strong>
        .
      </p>

      <blockquote>
        <p>
          <strong>Our Strict Privacy Promise</strong>: This license does{' '}
          <strong>not</strong> grant us the right to sell your User Content, distribute it to third
          parties for their independent use, or use your personal notes for advertising or marketing
          purposes. Furthermore, we contractually restrict our AI sub-processors (including
          Anthropic and Voyage AI) from using your note content to train their public models [2]
          [3]. No human employee or contractor at LivePsalms will ever read, review, or inspect your
          personal notes unless you explicitly request support and grant us temporary, express
          permission to access your account for troubleshooting.
        </p>
      </blockquote>

      <h3>4.3 User Representations and Warranties</h3>

      <p>You represent and warrant that:</p>

      <ul>
        <li>
          You own or have obtained all necessary licenses, rights, consents, and permissions to
          upload and process your User Content.
        </li>
        <li>
          Your User Content does not infringe, violate, or misappropriate any third-party
          intellectual property rights, privacy rights, or rights of publicity.
        </li>
        <li>Your User Content complies with our Acceptable Use Policy set forth in Section 6.</li>
      </ul>

      <hr />

      <h2>5. "Lamplight" AI Features and Output Terms</h2>

      <p>
        If you explicitly opt into our Lamplight AI feature suite, the following terms apply to your
        use of those features.
      </p>

      <h3>5.1 Nature of AI-Generated Output</h3>

      <p>
        Lamplight utilizes advanced large language models and text embedding technologies provided
        by third-party sub-processors (such as Anthropic and Voyage AI) to generate devotional
        reflections, summaries, and note connection explanations (collectively, "Output") [2] [3].
        You acknowledge and agree that:
      </p>

      <ul>
        <li>
          Generative AI outputs are probabilistic and may occasionally contain inaccurate,
          incomplete, or misleading information.
        </li>
        <li>
          The Output is generated automatically by machines and does not represent the theological
          positions, official doctrines, or personal views of LivePsalms.
        </li>
        <li>
          <strong>You must review and verify all Output before relying on it or sharing it.</strong>
        </li>
      </ul>

      <h3>5.2 Ownership of AI-Generated Output</h3>

      <p>
        Subject to your compliance with these Terms, LivePsalms assigns to you all of its rights,
        title, and interest (if any) in and to the Output generated for you by Lamplight.
      </p>

      <p>
        Under current copyright laws and regulatory guidance in major jurisdictions (including the
        United States Copyright Office), works generated entirely by artificial intelligence without
        meaningful human authorship may not be eligible for copyright protection [4]. LivePsalms
        makes no representations, warranties, or guarantees regarding the copyrightability, legal
        exclusivity, or proprietary protectability of any Output generated by the Services.
      </p>

      <h3>5.3 Non-Exclusivity of AI Output</h3>

      <p>
        Because of the nature of machine learning algorithms, similar prompts or thematic inputs
        from different users may occasionally result in identical or substantially similar Output.
        The assignment of rights in Section 5.2 does not apply to Output generated for other users,
        and you acknowledge that you cannot prevent other users from receiving similar
        machine-generated content.
      </p>

      <hr />

      <h2>6. Acceptable Use Policy</h2>

      <p>
        You agree to use the Services only for lawful purposes and in strict compliance with this
        Acceptable Use Policy.
      </p>

      <h3>6.1 Prohibited Activities</h3>

      <p>You shall not, and shall not permit or assist any third party to:</p>

      <ul>
        <li>
          Access or use the Services in any manner that violates any local, state, national, or
          international law or regulation.
        </li>
        <li>
          Upload, submit, or transmit any User Content that is defamatory, obscene, pornographic,
          harassing, threatening, hateful, or discriminatory on any basis, including race, sex,
          religion, nationality, disability, sexual orientation, or age.
        </li>
        <li>Use the Services to exploit, harm, or attempt to exploit or harm minors in any way.</li>
        <li>
          Upload or transmit any material that contains software viruses, Trojan horses, worms, time
          bombs, keystroke loggers, spyware, adware, or any other malicious or technologically
          harmful code designed to disrupt, damage, or limit the functionality of any computer
          software or hardware.
        </li>
        <li>
          Attempt to gain unauthorized access to, interfere with, damage, or disrupt any part of
          the Services, the servers on which our database is hosted, or any server, computer, or
          database connected to our platform.
        </li>
        <li>
          Attack our Services via a denial-of-service (DoS) attack or a distributed
          denial-of-service (DDoS) attack.
        </li>
        <li>
          Use any automated system, including "robots," "spiders," "offline readers," or
          "scrapers," to access the Services or extract data without our prior written authorization.
        </li>
        <li>
          Impersonate or attempt to impersonate LivePsalms, a LivePsalms employee, another user, or
          any other person or entity.
        </li>
      </ul>

      <h3>6.2 Reverse Engineering and AI Model Extraction Restrictions</h3>

      <p>You are strictly prohibited from:</p>

      <ul>
        <li>
          Reverse engineering, decompiling, disassembling, or otherwise attempting to discover the
          source code, object code, or underlying structure, ideas, or algorithms of our software or
          database architectures.
        </li>
        <li>
          Using the Services, including any Output generated by Lamplight, to train, develop,
          fine-tune, or improve any competing artificial intelligence models, machine learning
          systems, or software applications.
        </li>
        <li>
          Attempting to bypass, circumvent, or disable any security controls, digital rights
          management, rate limits, or authentication mechanisms implemented within our Services.
        </li>
      </ul>

      <hr />

      <h2>7. Intellectual Property of LivePsalms</h2>

      <p>
        Except for your User Content, the Services and all materials therein, including but not
        limited to software, source code, database structures, user interface designs, graphics,
        logos, trademarks, text, displays, images, video, and audio, and the selection,
        coordination, and arrangement thereof (collectively, the "LivePsalms IP"), are the exclusive
        property of LivePsalms, its licensors, or its suppliers, and are protected by United States
        and international copyright, trademark, patent, trade secret, and other intellectual
        property or proprietary rights laws.
      </p>

      <p>
        Subject to your compliance with these Terms and your payment of any applicable subscription
        fees, we grant you a limited, non-exclusive, non-transferable, non-sublicensable, revocable
        license to access and use the Services solely for your personal, non-commercial devotional
        study (or internal use within your local church or non-profit ministry).
      </p>

      <p>
        You must not copy, modify, translate, publish, distribute, transmit, sell, rent, lease, or
        create derivative works based on the LivePsalms IP without our prior, express written
        authorization.
      </p>

      <hr />

      <h2>8. Digital Millennium Copyright Act (DMCA) Policy</h2>

      <p>
        LivePsalms respects the intellectual property rights of others and expects its users to do
        the same. In accordance with the Digital Millennium Copyright Act (DMCA) [5], we will
        respond expeditiously to claims of copyright infringement committed on our platform if such
        claims are reported to our Designated Copyright Agent.
      </p>

      <h3>8.1 Filing an Infringement Notification</h3>

      <p>
        If you are a copyright owner, authorized to act on behalf of one, or authorized to act
        under any exclusive right under copyright, please report alleged copyright infringements
        taking place on or through our Services by sending a written DMCA Notice of Alleged
        Infringement containing the following information to our Designated Copyright Agent:
      </p>

      <ol>
        <li>
          A physical or electronic signature of a person authorized to act on behalf of the owner
          of an exclusive right that is allegedly infringed.
        </li>
        <li>
          Identification of the copyrighted work claimed to have been infringed, or, if multiple
          copyrighted works at a single online site are covered by a single notification, a
          representative list of such works at that site.
        </li>
        <li>
          Identification of the material that is claimed to be infringing or to be the subject of
          infringing activity and that is to be removed or access to which is to be disabled, and
          information reasonably sufficient to permit us to locate the material (including the
          specific URL or path).
        </li>
        <li>
          Information reasonably sufficient to permit us to contact you, such as an address,
          telephone number, and, if available, an electronic mail address at which you may be
          contacted.
        </li>
        <li>
          A statement that you have a good faith belief that use of the material in the manner
          complained of is not authorized by the copyright owner, its agent, or the law.
        </li>
        <li>
          A statement that the information in the notification is accurate, and under penalty of
          perjury, that you are authorized to act on behalf of the owner of an exclusive right that
          is allegedly infringed.
        </li>
      </ol>

      <p>Please deliver this notice to:</p>

      <ul>
        <li>
          <strong>Designated Copyright Agent</strong>: LivePsalms Legal Department, 17130 Van Buren
          Blvd, Unit 855, Riverside, CA 92504, USA
        </li>
        <li>
          <strong>Email</strong>:{' '}
          <a href="mailto:legal@livepsalms.com">legal@livepsalms.com</a>
        </li>
        <li>
          <strong>Phone</strong>: +1 (818) 800-4075
        </li>
      </ul>

      <h3>8.2 Repeat Infringer Policy</h3>

      <p>
        It is our policy, in appropriate circumstances and at our sole discretion, to disable and/or
        terminate the accounts of users who repeatedly infringe or are repeatedly charged with
        infringing the copyrights or other intellectual property rights of others.
      </p>

      <hr />

      <h2>9. Account Suspension and Termination</h2>

      <h3>9.1 Termination by You</h3>

      <p>
        You may terminate these Terms and close your LivePsalms account at any time for any reason
        by navigating to your Profile settings and selecting the "Delete Account" option. Upon
        selecting this option, your account will be immediately closed, and your data will be
        permanently deleted from our active databases in accordance with our Privacy Policy.
      </p>

      <h3>9.2 Suspension or Termination by Us</h3>

      <p>
        We reserve the right to suspend, restrict, or terminate your access to all or any part of
        the Services, with or without notice, at our sole discretion, if:
      </p>

      <ul>
        <li>
          You materially or repeatedly violate any provision of these Terms or our Acceptable Use
          Policy.
        </li>
        <li>
          You fail to pay any subscription fees when due, and fail to cure such non-payment within
          10 business days after receiving written notice of the failure.
        </li>
        <li>We are required to do so by applicable law, regulation, or government order.</li>
        <li>
          Your continued use of the Services poses a significant security, operational, or legal
          risk to LivePsalms, our sub-processors, or other users.
        </li>
      </ul>

      <h3>9.3 Effect of Termination</h3>

      <p>Upon termination of your account:</p>

      <ul>
        <li>
          All licenses granted to you under these Terms will immediately terminate, and you must
          cease all use of the Services.
        </li>
        <li>
          You will lose access to all User Content stored on our platform. We strongly encourage you
          to use our "Export Data" tool to download your notes and folders before requesting account
          deletion.
        </li>
        <li>
          Any outstanding payment obligations through the end of your current billing cycle will
          remain due and payable.
        </li>
        <li>
          Provisions of these Terms which by their nature should survive termination shall survive,
          including Section 4 (User Content ownership), Section 7 (LivePsalms IP), Section 10
          (Disclaimer of Warranties), Section 11 (Limitation of Liability), Section 12
          (Indemnification), Section 13 (Dispute Resolution), and Section 14 (Governing Law).
        </li>
      </ul>

      <hr />

      <h2>10. Disclaimer of Warranties</h2>

      <p>
        YOUR USE OF THE SERVICES, THE SERVICE MATERIALS, AND ANY OUTPUT GENERATED BY OUR AI
        FEATURES IS ENTIRELY AT YOUR OWN RISK. THE SERVICES ARE PROVIDED ON AN{' '}
        <strong>"AS IS"</strong> AND <strong>"AS AVAILABLE"</strong> BASIS, WITHOUT WARRANTIES OF
        ANY KIND, EITHER EXPRESS OR IMPLIED [6].
      </p>

      <p>
        TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, LIVEPSALMS DISCLAIMS ALL
        WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
      </p>

      <ul>
        <li>
          IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT.
        </li>
        <li>
          WARRANTIES THAT THE SERVICES WILL BE UNINTERRUPTED, SECURE, TIMELY, OR ERROR-FREE.
        </li>
        <li>
          WARRANTIES REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR THEOLOGICAL SOUNDNESS OF
          ANY CONTENT, BIBLE TRANSLATIONS, OR AI-GENERATED OUTPUT.
        </li>
        <li>
          WARRANTIES THAT ANY DEFECTS OR ERRORS IN THE SOFTWARE OR AI MODELS WILL BE CORRECTED.
        </li>
        <li>
          WARRANTIES THAT THE SERVICES OR THE SERVERS THAT MAKE THEM AVAILABLE ARE FREE OF VIRUSES
          OR OTHER HARMFUL COMPONENTS.
        </li>
      </ul>

      <p>
        NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM LIVEPSALMS OR
        THROUGH THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.
      </p>

      <hr />

      <h2>11. Limitation of Liability</h2>

      <p>
        TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, IN NO EVENT SHALL LIVEPSALMS, ITS
        AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, OR SUB-PROCESSORS BE LIABLE
        FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES,
        INCLUDING BUT NOT LIMITED TO:
      </p>

      <ul>
        <li>LOSS OF PROFITS, LOSS OF REVENUE, OR LOSS OF BUSINESS.</li>
        <li>LOSS OF DATA, LOSS OF USER CONTENT, OR CORRUPTION OF NOTES.</li>
        <li>LOSS OF GOODWILL, LOSS OF REPUTATION, OR USE DISRUPTION.</li>
        <li>
          PERSONAL INJURY, EMOTIONAL DISTRESS, OR SPIRITUAL ANXIETY ARISING OUT OF OR IN CONNECTION
          WITH YOUR USE OF OR INABILITY TO USE THE SERVICES, THE SERVICE MATERIALS, OR THE OUTPUT
          GENERATED BY OUR AI FEATURES.
        </li>
      </ul>

      <p>
        THESE LIMITATIONS APPLY REGARDLESS OF THE LEGAL THEORY UPON WHICH THE CLAIM IS BASED
        (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE), AND EVEN IF LIVEPSALMS HAS
        BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
      </p>

      <h3>Liability Cap</h3>

      <p>
        OUR AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE
        SERVICES SHALL NOT EXCEED THE TOTAL AMOUNT OF SUBSCRIPTION FEES PAID BY YOU TO LIVEPSALMS
        IN THE <strong>TWELVE (12) MONTHS</strong> IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO
        THE LIABILITY. IF YOU ARE A USER OF OUR FREE TIER, OUR MAXIMUM AGGREGATE LIABILITY SHALL
        NOT EXCEED <strong>FIFTY US DOLLARS ($50.00)</strong>.
      </p>

      <p>
        SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OF
        THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN SUCH JURISDICTIONS, OUR LIABILITY WILL BE
        LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.
      </p>

      <hr />

      <h2>12. Indemnification</h2>

      <p>
        You agree to defend, indemnify, and hold harmless LivePsalms, its affiliates, licensors,
        sub-processors, and all of their respective officers, directors, employees, contractors, and
        agents from and against any and all claims, liabilities, damages, losses, costs, expenses,
        or fees (including reasonable attorneys' fees) arising out of or relating to:
      </p>

      <ul>
        <li>Your violation or breach of these Terms or our Acceptable Use Policy.</li>
        <li>
          Your User Content, including any claims that your User Content infringes, violates, or
          misappropriates the intellectual property rights, privacy rights, or publicity rights of
          any third party.
        </li>
        <li>
          Your use of the Services, including any decisions made or actions taken by you in reliance
          on the Service Materials or Lamplight AI Output.
        </li>
        <li>
          Your violation of any applicable laws, regulations, or rights of another person or entity.
        </li>
      </ul>

      <p>
        LivePsalms reserves the right, at its own expense, to assume the exclusive defense and
        control of any matter otherwise subject to indemnification by you, in which event you agree
        to fully cooperate with LivePsalms in asserting any available defenses.
      </p>

      <hr />

      <h2>13. Dispute Resolution and Arbitration Agreement</h2>

      <p>
        <strong>
          PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO
          FILE A LAWSUIT IN COURT AND TO HAVE A JURY TRIAL.
        </strong>
      </p>

      <h3>13.1 Informal Dispute Resolution</h3>

      <p>
        Before filing a formal claim, you and LivePsalms agree to attempt to resolve any dispute,
        claim, or controversy arising out of or relating to these Terms or the Services (each, a
        "Dispute") informally. You can initiate this process by sending a written description of
        your Dispute, along with your contact information and proposed resolution, to{' '}
        <a href="mailto:legal@livepsalms.com">legal@livepsalms.com</a>. LivePsalms will contact you
        at the email address associated with your account. If we are unable to resolve the Dispute
        within sixty (60) days of the initial notification, either party may proceed to file a
        formal arbitration request as detailed below.
      </p>

      <h3>13.2 Mandatory Binding Arbitration</h3>

      <p>
        If informal resolution fails, you and LivePsalms agree that any Dispute shall be settled by{' '}
        <strong>binding, individual arbitration</strong> administered by the American Arbitration
        Association (AAA) in accordance with its Consumer Arbitration Rules [7]. The arbitration
        shall be conducted by a single, neutral arbitrator.
      </p>

      <p>
        The arbitration shall take place in Dallas, Texas, unless you and LivePsalms mutually agree
        on a different location or select remote virtual proceedings. The arbitrator's decision
        shall be final and binding, and judgment on the award rendered by the arbitrator may be
        entered in any court having jurisdiction thereof.
      </p>

      <h3>13.3 Class Action Waiver</h3>

      <p>
        <strong>
          YOU AND LIVEPSALMS AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN
          INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS,
          REPRESENTATIVE, OR MULTI-DISTRICT PROCEEDING [8].
        </strong>
      </p>

      <p>
        The arbitrator may not consolidate more than one person's claims, and may not otherwise
        preside over any form of a class or representative proceeding unless both you and
        LivePsalms explicitly agree in writing. If this specific Class Action Waiver is found to be
        unenforceable, then the entirety of this Section 13 (except for Section 13.5) shall be null
        and void.
      </p>

      <h3>13.4 Jury Trial Waiver</h3>

      <p>
        BY AGREEING TO THESE TERMS,{' '}
        <strong>YOU AND LIVEPSALMS ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY</strong> AND THE
        RIGHT TO HAVE DISPUTES RESOLVED IN A COURT OF LAW. You acknowledge that arbitration is more
        informal, has limited discovery, and is subject to very limited review by courts.
      </p>

      <h3>13.5 Exceptions to Arbitration</h3>

      <p>Notwithstanding the agreement to arbitrate, either party may:</p>

      <ul>
        <li>
          Bring an individual action in a small claims court of competent jurisdiction.
        </li>
        <li>
          Seek injunctive or other equitable relief in a court of competent jurisdiction to prevent
          the actual or threatened infringement, misappropriation, or violation of a party's
          copyrights, trademarks, trade secrets, patents, or other intellectual property rights.
        </li>
      </ul>

      <h3>13.6 Arbitration Opt-Out Right</h3>

      <p>
        You have the right to opt out of the mandatory arbitration and class action waiver
        provisions of this Section 13. To opt out, you must send a written opt-out notice to{' '}
        <a href="mailto:legal@livepsalms.com">legal@livepsalms.com</a> within{' '}
        <strong>thirty (30) days</strong> of the date you first created your LivePsalms account.
        Your opt-out notice must include:
      </p>

      <ul>
        <li>Your full name.</li>
        <li>The email address associated with your LivePsalms account.</li>
        <li>
          A clear statement that you wish to opt out of the arbitration agreement and class action
          waiver.
        </li>
      </ul>

      <p>
        If you opt out in compliance with this section, all other parts of these Terms, including
        Section 14 (Governing Law), will continue to apply to you.
      </p>

      <hr />

      <h2>14. Governing Law and Jurisdiction</h2>

      <p>
        These Terms, and any Dispute arising out of or relating to them, shall be governed by,
        construed, and enforced in accordance with the laws of the{' '}
        <strong>State of Texas</strong>, United States, without regard to its conflict of law
        principles.
      </p>

      <p>
        To the extent that any Dispute is permitted to be brought in a court of law under Section
        13.5 or because you opted out of arbitration under Section 13.6, you and LivePsalms agree
        that such actions shall be filed exclusively in the state or federal courts located in{' '}
        <strong>Dallas County, Texas</strong>, and you hereby consent to the personal jurisdiction
        and venue of such courts.
      </p>

      <hr />

      <h2>15. Force Majeure</h2>

      <p>
        LivePsalms shall not be liable or responsible to you, nor be deemed to have defaulted under
        or breached these Terms, for any failure or delay in fulfilling or performing our
        obligations when such failure or delay is caused by or results from acts or circumstances
        beyond our reasonable control (a "Force Majeure Event") [9].
      </p>

      <p>Force Majeure Events include, but are not limited to:</p>

      <ul>
        <li>Acts of God, flood, fire, earthquake, or other natural disasters.</li>
        <li>
          War, invasion, hostilities (whether war is declared or not), terrorist threats or acts,
          riot, or other civil unrest.
        </li>
        <li>Government order, law, actions, or national or regional emergencies.</li>
        <li>Epidemics, pandemics, or public health crises.</li>
        <li>Strikes, labor disputes, or industrial disturbances.</li>
        <li>
          Widespread internet outages, telecommunications failures, power grid disruptions, or
          failures of third-party infrastructure providers (including cloud hosting or AI API
          service interruptions) [9].
        </li>
      </ul>

      <p>
        In the event of a Force Majeure Event, we will make reasonable efforts to mitigate the
        disruption and restore access to the Services as quickly as possible.
      </p>

      <hr />

      <h2>16. General Provisions</h2>

      <h3>16.1 Entire Agreement</h3>

      <p>
        These Terms, together with our Privacy Policy and any subscription order confirmations,
        constitute the entire agreement between you and LivePsalms regarding your access to and use
        of the Services, and supersede all prior or contemporaneous understandings, agreements, or
        discussions, whether written or oral, regarding the subject matter.
      </p>

      <h3>16.2 Modifications to These Terms</h3>

      <p>
        We reserve the right to modify or update these Terms at any time. When we make changes, we
        will update the "Last Updated" date at the top of this page. For material changes, we will
        provide you with at least 30 days' advance notice via email or a prominent notification
        within the application. Your continued use of the Services after the expiration of the
        notice period constitutes your acceptance of the modified Terms. If you do not agree to the
        modified Terms, you must stop using the Services and delete your account.
      </p>

      <h3>16.3 Severability</h3>

      <p>
        If any provision of these Terms is found by an arbitrator or court of competent jurisdiction
        to be invalid, illegal, or unenforceable, such provision shall be eliminated or limited to
        the minimum extent necessary, and the remaining provisions of these Terms shall remain in
        full force and effect.
      </p>

      <h3>16.4 Waiver</h3>

      <p>
        No waiver by LivePsalms of any term or condition set forth in these Terms shall be deemed a
        further or continuing waiver of such term or condition or a waiver of any other term or
        condition, and any failure of LivePsalms to assert a right or provision under these Terms
        shall not constitute a waiver of such right or provision.
      </p>

      <h3>16.5 Assignment</h3>

      <p>
        You may not assign, transfer, or delegate your rights or obligations under these Terms
        without our prior written consent. LivePsalms may freely assign, transfer, or delegate its
        rights and obligations under these Terms without restriction or notice to you.
      </p>

      <hr />

      <h2>References</h2>

      <ul>
        <li>
          [1]{' '}
          <a
            href="https://gdpr-info.eu/art-8-gdpr/"
            target="_blank"
            rel="noopener noreferrer"
          >
            EU General Data Protection Regulation (GDPR) — Article 8: Age of Consent
          </a>
        </li>
        <li>
          [2]{' '}
          <a
            href="https://privacy.claude.com/en/articles/7996868-is-my-data-used-for-model-training"
            target="_blank"
            rel="noopener noreferrer"
          >
            Anthropic Commercial Terms and API Data Usage Policy
          </a>
        </li>
        <li>
          [3]{' '}
          <a
            href="https://www.voyageai.com/tos"
            target="_blank"
            rel="noopener noreferrer"
          >
            Voyage AI Terms of Service — Section 3: Content and Models
          </a>
        </li>
        <li>
          [4]{' '}
          <a
            href="https://www.openpolicy.co/resources/u-s-copyright-office-clarifies-ai-authorship-rules-in-part-ii-of-its-copyright-ai-report"
            target="_blank"
            rel="noopener noreferrer"
          >
            U.S. Copyright Office Guidance on AI-Generated Works
          </a>
        </li>
        <li>
          [5]{' '}
          <a
            href="https://www.copyright.gov/512/"
            target="_blank"
            rel="noopener noreferrer"
          >
            U.S. Copyright Office — DMCA Safe Harbor Provisions
          </a>
        </li>
        <li>
          [6]{' '}
          <a
            href="https://www.termsfeed.com/blog/as-is-as-available-legal-agreements/"
            target="_blank"
            rel="noopener noreferrer"
          >
            "As Is" and "As Available" Disclaimers in Online Agreements
          </a>
        </li>
        <li>
          [7]{' '}
          <a
            href="https://www.mbm-law.net/insights/enforceable-online-arbitration-pa/"
            target="_blank"
            rel="noopener noreferrer"
          >
            American Arbitration Association (AAA) Consumer Rules
          </a>
        </li>
        <li>
          [8]{' '}
          <a
            href="https://www.termsfeed.com/blog/class-action-waivers-terms-conditions/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Class Action Waivers in Consumer Terms and Conditions
          </a>
        </li>
        <li>
          [9]{' '}
          <a
            href="https://www.carusolawoffice.com/post/b2b-saas-agreements-mitigate-risk-with-force-majeure-clauses"
            target="_blank"
            rel="noopener noreferrer"
          >
            Force Majeure Clauses in SaaS and Cloud Service Agreements
          </a>
        </li>
      </ul>
    </LegalPage>
  );
}
