// AUTO-GENERATED by scripts/build-style-assets.mjs — do not edit by hand.
import { findAsset, filterAssets } from './asset-helpers';

export type StyleCategory =
  | 'highlight' | 'shape' | 'arrow' | 'bubble' | 'squiggle' | 'line';

export interface StyleAsset {
  id: string;
  category: StyleCategory;
  thumbUrl: string;
  displayUrl: string;
  aspectRatio: number;
}

export const STYLE_ASSETS: StyleAsset[] = [
  {
    "id": "arrow-01",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-01.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-01.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-02",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-02.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-02.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-03",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-03.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-03.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-04",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-04.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-04.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-05",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-05.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-05.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-06",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-06.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-06.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-07",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-07.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-07.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-08",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-08.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-08.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-09",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-09.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-09.webp",
    "aspectRatio": 0.6086
  },
  {
    "id": "arrow-10",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-10.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-10.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-11",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-11.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-11.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-12",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-12.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-12.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-13",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-13.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-13.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-14",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-14.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-14.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-15",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-15.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-15.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-16",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-16.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-16.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-17",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-17.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-17.webp",
    "aspectRatio": 0.8473
  },
  {
    "id": "arrow-18",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-18.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-18.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-19",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-19.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-19.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-20",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-20.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-20.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-21",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-21.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-21.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-22",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-22.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-22.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-23",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-23.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-23.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-24",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-24.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-24.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-25",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-25.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-25.webp",
    "aspectRatio": 1.5104
  },
  {
    "id": "arrow-26",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-26.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-26.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-27",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-27.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-27.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-28",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-28.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-28.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-29",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-29.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-29.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-30",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-30.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-30.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-31",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-31.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-31.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-32",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-32.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-32.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-33",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-33.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-33.webp",
    "aspectRatio": 1.1507
  },
  {
    "id": "arrow-34",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-34.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-34.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-35",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-35.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-35.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-36",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-36.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-36.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-37",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-37.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-37.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-38",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-38.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-38.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-39",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-39.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-39.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-40",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-40.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-40.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-41",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-41.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-41.webp",
    "aspectRatio": 0.9898
  },
  {
    "id": "arrow-42",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-42.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-42.webp",
    "aspectRatio": 0.8976
  },
  {
    "id": "arrow-43",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-43.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-43.webp",
    "aspectRatio": 0.8976
  },
  {
    "id": "arrow-44",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-44.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-44.webp",
    "aspectRatio": 0.8976
  },
  {
    "id": "arrow-45",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-45.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-45.webp",
    "aspectRatio": 0.8976
  },
  {
    "id": "arrow-46",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-46.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-46.webp",
    "aspectRatio": 0.8976
  },
  {
    "id": "arrow-47",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-47.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-47.webp",
    "aspectRatio": 0.8976
  },
  {
    "id": "arrow-48",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-48.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-48.webp",
    "aspectRatio": 0.8976
  },
  {
    "id": "arrow-49",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-49.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-49.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-50",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-50.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-50.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-51",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-51.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-51.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-52",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-52.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-52.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-53",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-53.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-53.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-54",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-54.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-54.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-55",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-55.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-55.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-56",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-56.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-56.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-57",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-57.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-57.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-58",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-58.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-58.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-59",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-59.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-59.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "arrow-60",
    "category": "arrow",
    "thumbUrl": "/styles/arrow/arrow-60.thumb.webp",
    "displayUrl": "/styles/arrow/arrow-60.webp",
    "aspectRatio": 3.9195
  },
  {
    "id": "bubble-01",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-01.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-01.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-02",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-02.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-02.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-03",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-03.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-03.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-04",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-04.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-04.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-05",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-05.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-05.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-06",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-06.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-06.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-07",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-07.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-07.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-08",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-08.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-08.webp",
    "aspectRatio": 1.5406
  },
  {
    "id": "bubble-09",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-09.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-09.webp",
    "aspectRatio": 1.2574
  },
  {
    "id": "bubble-10",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-10.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-10.webp",
    "aspectRatio": 1.2574
  },
  {
    "id": "bubble-11",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-11.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-11.webp",
    "aspectRatio": 1.2574
  },
  {
    "id": "bubble-12",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-12.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-12.webp",
    "aspectRatio": 1.2574
  },
  {
    "id": "bubble-13",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-13.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-13.webp",
    "aspectRatio": 1.2574
  },
  {
    "id": "bubble-14",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-14.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-14.webp",
    "aspectRatio": 1.2574
  },
  {
    "id": "bubble-15",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-15.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-15.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-16",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-16.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-16.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-17",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-17.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-17.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-18",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-18.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-18.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-19",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-19.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-19.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-20",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-20.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-20.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-21",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-21.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-21.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-22",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-22.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-22.webp",
    "aspectRatio": 1.7179
  },
  {
    "id": "bubble-23",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-23.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-23.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-24",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-24.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-24.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-25",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-25.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-25.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-26",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-26.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-26.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-27",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-27.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-27.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-28",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-28.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-28.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-29",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-29.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-29.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-30",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-30.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-30.webp",
    "aspectRatio": 1.4843
  },
  {
    "id": "bubble-31",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-31.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-31.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-32",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-32.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-32.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-33",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-33.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-33.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-35",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-35.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-35.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-36",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-36.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-36.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-37",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-37.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-37.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-38",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-38.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-38.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-39",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-39.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-39.webp",
    "aspectRatio": 0.6936
  },
  {
    "id": "bubble-40",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-40.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-40.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-41",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-41.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-41.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-42",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-42.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-42.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-43",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-43.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-43.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-44",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-44.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-44.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-45",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-45.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-45.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-46",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-46.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-46.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-47",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-47.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-47.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-48",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-48.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-48.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "bubble-49",
    "category": "bubble",
    "thumbUrl": "/styles/bubble/bubble-49.thumb.webp",
    "displayUrl": "/styles/bubble/bubble-49.webp",
    "aspectRatio": 1.6964
  },
  {
    "id": "highlight-01",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-01.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-01.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-02",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-02.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-02.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-03",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-03.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-03.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-04",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-04.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-04.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-05",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-05.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-05.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-06",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-06.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-06.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-07",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-07.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-07.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-08",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-08.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-08.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-09",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-09.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-09.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-10",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-10.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-10.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-100",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-100.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-100.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "highlight-101",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-101.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-101.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "highlight-102",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-102.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-102.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "highlight-103",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-103.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-103.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "highlight-104",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-104.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-104.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "highlight-105",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-105.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-105.webp",
    "aspectRatio": 1.0275
  },
  {
    "id": "highlight-106",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-106.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-106.webp",
    "aspectRatio": 1.0275
  },
  {
    "id": "highlight-107",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-107.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-107.webp",
    "aspectRatio": 1.0275
  },
  {
    "id": "highlight-108",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-108.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-108.webp",
    "aspectRatio": 1.0275
  },
  {
    "id": "highlight-109",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-109.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-109.webp",
    "aspectRatio": 1.0275
  },
  {
    "id": "highlight-11",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-11.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-11.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-110",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-110.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-110.webp",
    "aspectRatio": 1.0275
  },
  {
    "id": "highlight-111",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-111.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-111.webp",
    "aspectRatio": 1.0275
  },
  {
    "id": "highlight-112",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-112.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-112.webp",
    "aspectRatio": 5.7139
  },
  {
    "id": "highlight-113",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-113.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-113.webp",
    "aspectRatio": 6.024
  },
  {
    "id": "highlight-114",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-114.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-114.webp",
    "aspectRatio": 8.6298
  },
  {
    "id": "highlight-115",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-115.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-115.webp",
    "aspectRatio": 8.4983
  },
  {
    "id": "highlight-116",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-116.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-116.webp",
    "aspectRatio": 6.7017
  },
  {
    "id": "highlight-117",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-117.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-117.webp",
    "aspectRatio": 3.5409
  },
  {
    "id": "highlight-118",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-118.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-118.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-119",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-119.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-119.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-12",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-12.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-12.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-120",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-120.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-120.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-121",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-121.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-121.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-122",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-122.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-122.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-123",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-123.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-123.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-124",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-124.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-124.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-125",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-125.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-125.webp",
    "aspectRatio": 2.0883
  },
  {
    "id": "highlight-13",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-13.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-13.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-14",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-14.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-14.webp",
    "aspectRatio": 1
  },
  {
    "id": "highlight-15",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-15.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-15.webp",
    "aspectRatio": 1.549
  },
  {
    "id": "highlight-16",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-16.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-16.webp",
    "aspectRatio": 1.5441
  },
  {
    "id": "highlight-17",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-17.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-17.webp",
    "aspectRatio": 1.5441
  },
  {
    "id": "highlight-18",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-18.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-18.webp",
    "aspectRatio": 1.5575
  },
  {
    "id": "highlight-19",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-19.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-19.webp",
    "aspectRatio": 1.5441
  },
  {
    "id": "highlight-20",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-20.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-20.webp",
    "aspectRatio": 1.5441
  },
  {
    "id": "highlight-21",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-21.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-21.webp",
    "aspectRatio": 1.5441
  },
  {
    "id": "highlight-22",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-22.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-22.webp",
    "aspectRatio": 4.884
  },
  {
    "id": "highlight-23",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-23.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-23.webp",
    "aspectRatio": 4.884
  },
  {
    "id": "highlight-24",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-24.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-24.webp",
    "aspectRatio": 4.884
  },
  {
    "id": "highlight-25",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-25.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-25.webp",
    "aspectRatio": 4.884
  },
  {
    "id": "highlight-26",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-26.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-26.webp",
    "aspectRatio": 4.884
  },
  {
    "id": "highlight-27",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-27.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-27.webp",
    "aspectRatio": 4.884
  },
  {
    "id": "highlight-28",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-28.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-28.webp",
    "aspectRatio": 4.884
  },
  {
    "id": "highlight-29",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-29.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-29.webp",
    "aspectRatio": 10.886
  },
  {
    "id": "highlight-30",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-30.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-30.webp",
    "aspectRatio": 10.886
  },
  {
    "id": "highlight-31",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-31.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-31.webp",
    "aspectRatio": 10.886
  },
  {
    "id": "highlight-32",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-32.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-32.webp",
    "aspectRatio": 10.886
  },
  {
    "id": "highlight-33",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-33.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-33.webp",
    "aspectRatio": 10.886
  },
  {
    "id": "highlight-34",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-34.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-34.webp",
    "aspectRatio": 4.2224
  },
  {
    "id": "highlight-35",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-35.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-35.webp",
    "aspectRatio": 4.2224
  },
  {
    "id": "highlight-36",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-36.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-36.webp",
    "aspectRatio": 4.2224
  },
  {
    "id": "highlight-37",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-37.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-37.webp",
    "aspectRatio": 4.2224
  },
  {
    "id": "highlight-38",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-38.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-38.webp",
    "aspectRatio": 9.051
  },
  {
    "id": "highlight-39",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-39.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-39.webp",
    "aspectRatio": 9.051
  },
  {
    "id": "highlight-40",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-40.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-40.webp",
    "aspectRatio": 9.051
  },
  {
    "id": "highlight-41",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-41.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-41.webp",
    "aspectRatio": 9.051
  },
  {
    "id": "highlight-42",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-42.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-42.webp",
    "aspectRatio": 9.051
  },
  {
    "id": "highlight-43",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-43.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-43.webp",
    "aspectRatio": 9.051
  },
  {
    "id": "highlight-44",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-44.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-44.webp",
    "aspectRatio": 9.051
  },
  {
    "id": "highlight-45",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-45.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-45.webp",
    "aspectRatio": 3.3056
  },
  {
    "id": "highlight-46",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-46.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-46.webp",
    "aspectRatio": 3.3056
  },
  {
    "id": "highlight-47",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-47.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-47.webp",
    "aspectRatio": 3.3056
  },
  {
    "id": "highlight-48",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-48.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-48.webp",
    "aspectRatio": 3.3056
  },
  {
    "id": "highlight-49",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-49.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-49.webp",
    "aspectRatio": 3.3056
  },
  {
    "id": "highlight-50",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-50.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-50.webp",
    "aspectRatio": 3.3056
  },
  {
    "id": "highlight-51",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-51.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-51.webp",
    "aspectRatio": 1.5414
  },
  {
    "id": "highlight-52",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-52.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-52.webp",
    "aspectRatio": 1.5414
  },
  {
    "id": "highlight-53",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-53.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-53.webp",
    "aspectRatio": 1.5414
  },
  {
    "id": "highlight-54",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-54.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-54.webp",
    "aspectRatio": 1.5414
  },
  {
    "id": "highlight-55",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-55.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-55.webp",
    "aspectRatio": 1.5414
  },
  {
    "id": "highlight-56",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-56.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-56.webp",
    "aspectRatio": 1.5414
  },
  {
    "id": "highlight-57",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-57.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-57.webp",
    "aspectRatio": 1.5414
  },
  {
    "id": "highlight-58",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-58.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-58.webp",
    "aspectRatio": 6
  },
  {
    "id": "highlight-59",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-59.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-59.webp",
    "aspectRatio": 6
  },
  {
    "id": "highlight-60",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-60.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-60.webp",
    "aspectRatio": 6
  },
  {
    "id": "highlight-61",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-61.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-61.webp",
    "aspectRatio": 6
  },
  {
    "id": "highlight-62",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-62.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-62.webp",
    "aspectRatio": 6
  },
  {
    "id": "highlight-63",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-63.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-63.webp",
    "aspectRatio": 6
  },
  {
    "id": "highlight-64",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-64.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-64.webp",
    "aspectRatio": 6.1008
  },
  {
    "id": "highlight-65",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-65.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-65.webp",
    "aspectRatio": 6.1008
  },
  {
    "id": "highlight-66",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-66.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-66.webp",
    "aspectRatio": 6.1008
  },
  {
    "id": "highlight-67",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-67.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-67.webp",
    "aspectRatio": 6.1008
  },
  {
    "id": "highlight-68",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-68.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-68.webp",
    "aspectRatio": 6.1008
  },
  {
    "id": "highlight-69",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-69.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-69.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-70",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-70.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-70.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-71",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-71.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-71.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-72",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-72.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-72.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-73",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-73.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-73.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-74",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-74.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-74.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-75",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-75.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-75.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-76",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-76.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-76.webp",
    "aspectRatio": 3.5863
  },
  {
    "id": "highlight-77",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-77.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-77.webp",
    "aspectRatio": 4.4581
  },
  {
    "id": "highlight-78",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-78.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-78.webp",
    "aspectRatio": 4.4581
  },
  {
    "id": "highlight-79",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-79.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-79.webp",
    "aspectRatio": 4.4581
  },
  {
    "id": "highlight-80",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-80.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-80.webp",
    "aspectRatio": 4.4581
  },
  {
    "id": "highlight-81",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-81.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-81.webp",
    "aspectRatio": 4.4581
  },
  {
    "id": "highlight-82",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-82.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-82.webp",
    "aspectRatio": 4.4581
  },
  {
    "id": "highlight-83",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-83.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-83.webp",
    "aspectRatio": 6.073
  },
  {
    "id": "highlight-84",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-84.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-84.webp",
    "aspectRatio": 6.073
  },
  {
    "id": "highlight-85",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-85.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-85.webp",
    "aspectRatio": 6.073
  },
  {
    "id": "highlight-86",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-86.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-86.webp",
    "aspectRatio": 6.073
  },
  {
    "id": "highlight-87",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-87.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-87.webp",
    "aspectRatio": 6.073
  },
  {
    "id": "highlight-88",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-88.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-88.webp",
    "aspectRatio": 6.073
  },
  {
    "id": "highlight-89",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-89.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-89.webp",
    "aspectRatio": 6.073
  },
  {
    "id": "highlight-90",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-90.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-90.webp",
    "aspectRatio": 4.0728
  },
  {
    "id": "highlight-91",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-91.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-91.webp",
    "aspectRatio": 4.0728
  },
  {
    "id": "highlight-92",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-92.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-92.webp",
    "aspectRatio": 4.0728
  },
  {
    "id": "highlight-93",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-93.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-93.webp",
    "aspectRatio": 4.0728
  },
  {
    "id": "highlight-94",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-94.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-94.webp",
    "aspectRatio": 4.0728
  },
  {
    "id": "highlight-95",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-95.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-95.webp",
    "aspectRatio": 4.0728
  },
  {
    "id": "highlight-96",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-96.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-96.webp",
    "aspectRatio": 4.0728
  },
  {
    "id": "highlight-97",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-97.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-97.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "highlight-98",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-98.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-98.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "highlight-99",
    "category": "highlight",
    "thumbUrl": "/styles/highlight/highlight-99.thumb.webp",
    "displayUrl": "/styles/highlight/highlight-99.webp",
    "aspectRatio": 1.6559
  },
  {
    "id": "line-01",
    "category": "line",
    "thumbUrl": "/styles/line/line-01.thumb.webp",
    "displayUrl": "/styles/line/line-01.webp",
    "aspectRatio": 165.8696
  },
  {
    "id": "line-02",
    "category": "line",
    "thumbUrl": "/styles/line/line-02.thumb.webp",
    "displayUrl": "/styles/line/line-02.webp",
    "aspectRatio": 165.8696
  },
  {
    "id": "line-03",
    "category": "line",
    "thumbUrl": "/styles/line/line-03.thumb.webp",
    "displayUrl": "/styles/line/line-03.webp",
    "aspectRatio": 165.8696
  },
  {
    "id": "line-04",
    "category": "line",
    "thumbUrl": "/styles/line/line-04.thumb.webp",
    "displayUrl": "/styles/line/line-04.webp",
    "aspectRatio": 165.8696
  },
  {
    "id": "line-05",
    "category": "line",
    "thumbUrl": "/styles/line/line-05.thumb.webp",
    "displayUrl": "/styles/line/line-05.webp",
    "aspectRatio": 165.8696
  },
  {
    "id": "line-06",
    "category": "line",
    "thumbUrl": "/styles/line/line-06.thumb.webp",
    "displayUrl": "/styles/line/line-06.webp",
    "aspectRatio": 165.8696
  },
  {
    "id": "line-07",
    "category": "line",
    "thumbUrl": "/styles/line/line-07.thumb.webp",
    "displayUrl": "/styles/line/line-07.webp",
    "aspectRatio": 174.037
  },
  {
    "id": "line-08",
    "category": "line",
    "thumbUrl": "/styles/line/line-08.thumb.webp",
    "displayUrl": "/styles/line/line-08.webp",
    "aspectRatio": 174.037
  },
  {
    "id": "line-09",
    "category": "line",
    "thumbUrl": "/styles/line/line-09.thumb.webp",
    "displayUrl": "/styles/line/line-09.webp",
    "aspectRatio": 174.037
  },
  {
    "id": "line-10",
    "category": "line",
    "thumbUrl": "/styles/line/line-10.thumb.webp",
    "displayUrl": "/styles/line/line-10.webp",
    "aspectRatio": 174.037
  },
  {
    "id": "line-11",
    "category": "line",
    "thumbUrl": "/styles/line/line-11.thumb.webp",
    "displayUrl": "/styles/line/line-11.webp",
    "aspectRatio": 174.037
  },
  {
    "id": "line-13",
    "category": "line",
    "thumbUrl": "/styles/line/line-13.thumb.webp",
    "displayUrl": "/styles/line/line-13.webp",
    "aspectRatio": 174.037
  },
  {
    "id": "line-14",
    "category": "line",
    "thumbUrl": "/styles/line/line-14.thumb.webp",
    "displayUrl": "/styles/line/line-14.webp",
    "aspectRatio": 71.6852
  },
  {
    "id": "line-15",
    "category": "line",
    "thumbUrl": "/styles/line/line-15.thumb.webp",
    "displayUrl": "/styles/line/line-15.webp",
    "aspectRatio": 71.6852
  },
  {
    "id": "line-16",
    "category": "line",
    "thumbUrl": "/styles/line/line-16.thumb.webp",
    "displayUrl": "/styles/line/line-16.webp",
    "aspectRatio": 71.6852
  },
  {
    "id": "line-17",
    "category": "line",
    "thumbUrl": "/styles/line/line-17.thumb.webp",
    "displayUrl": "/styles/line/line-17.webp",
    "aspectRatio": 71.6852
  },
  {
    "id": "line-18",
    "category": "line",
    "thumbUrl": "/styles/line/line-18.thumb.webp",
    "displayUrl": "/styles/line/line-18.webp",
    "aspectRatio": 71.6852
  },
  {
    "id": "line-19",
    "category": "line",
    "thumbUrl": "/styles/line/line-19.thumb.webp",
    "displayUrl": "/styles/line/line-19.webp",
    "aspectRatio": 71.6852
  },
  {
    "id": "line-20",
    "category": "line",
    "thumbUrl": "/styles/line/line-20.thumb.webp",
    "displayUrl": "/styles/line/line-20.webp",
    "aspectRatio": 71.6852
  },
  {
    "id": "line-21",
    "category": "line",
    "thumbUrl": "/styles/line/line-21.thumb.webp",
    "displayUrl": "/styles/line/line-21.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-22",
    "category": "line",
    "thumbUrl": "/styles/line/line-22.thumb.webp",
    "displayUrl": "/styles/line/line-22.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-23",
    "category": "line",
    "thumbUrl": "/styles/line/line-23.thumb.webp",
    "displayUrl": "/styles/line/line-23.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-24",
    "category": "line",
    "thumbUrl": "/styles/line/line-24.thumb.webp",
    "displayUrl": "/styles/line/line-24.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-25",
    "category": "line",
    "thumbUrl": "/styles/line/line-25.thumb.webp",
    "displayUrl": "/styles/line/line-25.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-26",
    "category": "line",
    "thumbUrl": "/styles/line/line-26.thumb.webp",
    "displayUrl": "/styles/line/line-26.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-27",
    "category": "line",
    "thumbUrl": "/styles/line/line-27.thumb.webp",
    "displayUrl": "/styles/line/line-27.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-28",
    "category": "line",
    "thumbUrl": "/styles/line/line-28.thumb.webp",
    "displayUrl": "/styles/line/line-28.webp",
    "aspectRatio": 50.3372
  },
  {
    "id": "line-29",
    "category": "line",
    "thumbUrl": "/styles/line/line-29.thumb.webp",
    "displayUrl": "/styles/line/line-29.webp",
    "aspectRatio": 17.5925
  },
  {
    "id": "line-30",
    "category": "line",
    "thumbUrl": "/styles/line/line-30.thumb.webp",
    "displayUrl": "/styles/line/line-30.webp",
    "aspectRatio": 17.5925
  },
  {
    "id": "line-31",
    "category": "line",
    "thumbUrl": "/styles/line/line-31.thumb.webp",
    "displayUrl": "/styles/line/line-31.webp",
    "aspectRatio": 17.5925
  },
  {
    "id": "line-32",
    "category": "line",
    "thumbUrl": "/styles/line/line-32.thumb.webp",
    "displayUrl": "/styles/line/line-32.webp",
    "aspectRatio": 17.5925
  },
  {
    "id": "line-33",
    "category": "line",
    "thumbUrl": "/styles/line/line-33.thumb.webp",
    "displayUrl": "/styles/line/line-33.webp",
    "aspectRatio": 17.5925
  },
  {
    "id": "line-34",
    "category": "line",
    "thumbUrl": "/styles/line/line-34.thumb.webp",
    "displayUrl": "/styles/line/line-34.webp",
    "aspectRatio": 17.5925
  },
  {
    "id": "line-35",
    "category": "line",
    "thumbUrl": "/styles/line/line-35.thumb.webp",
    "displayUrl": "/styles/line/line-35.webp",
    "aspectRatio": 29.5032
  },
  {
    "id": "line-36",
    "category": "line",
    "thumbUrl": "/styles/line/line-36.thumb.webp",
    "displayUrl": "/styles/line/line-36.webp",
    "aspectRatio": 29.5032
  },
  {
    "id": "line-37",
    "category": "line",
    "thumbUrl": "/styles/line/line-37.thumb.webp",
    "displayUrl": "/styles/line/line-37.webp",
    "aspectRatio": 29.5032
  },
  {
    "id": "line-38",
    "category": "line",
    "thumbUrl": "/styles/line/line-38.thumb.webp",
    "displayUrl": "/styles/line/line-38.webp",
    "aspectRatio": 29.5032
  },
  {
    "id": "line-39",
    "category": "line",
    "thumbUrl": "/styles/line/line-39.thumb.webp",
    "displayUrl": "/styles/line/line-39.webp",
    "aspectRatio": 29.5032
  },
  {
    "id": "line-40",
    "category": "line",
    "thumbUrl": "/styles/line/line-40.thumb.webp",
    "displayUrl": "/styles/line/line-40.webp",
    "aspectRatio": 29.5032
  },
  {
    "id": "line-41",
    "category": "line",
    "thumbUrl": "/styles/line/line-41.thumb.webp",
    "displayUrl": "/styles/line/line-41.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-42",
    "category": "line",
    "thumbUrl": "/styles/line/line-42.thumb.webp",
    "displayUrl": "/styles/line/line-42.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-43",
    "category": "line",
    "thumbUrl": "/styles/line/line-43.thumb.webp",
    "displayUrl": "/styles/line/line-43.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-44",
    "category": "line",
    "thumbUrl": "/styles/line/line-44.thumb.webp",
    "displayUrl": "/styles/line/line-44.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-45",
    "category": "line",
    "thumbUrl": "/styles/line/line-45.thumb.webp",
    "displayUrl": "/styles/line/line-45.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-46",
    "category": "line",
    "thumbUrl": "/styles/line/line-46.thumb.webp",
    "displayUrl": "/styles/line/line-46.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-47",
    "category": "line",
    "thumbUrl": "/styles/line/line-47.thumb.webp",
    "displayUrl": "/styles/line/line-47.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-48",
    "category": "line",
    "thumbUrl": "/styles/line/line-48.thumb.webp",
    "displayUrl": "/styles/line/line-48.webp",
    "aspectRatio": 15.6289
  },
  {
    "id": "line-49",
    "category": "line",
    "thumbUrl": "/styles/line/line-49.thumb.webp",
    "displayUrl": "/styles/line/line-49.webp",
    "aspectRatio": 40.2598
  },
  {
    "id": "line-50",
    "category": "line",
    "thumbUrl": "/styles/line/line-50.thumb.webp",
    "displayUrl": "/styles/line/line-50.webp",
    "aspectRatio": 40.2598
  },
  {
    "id": "line-51",
    "category": "line",
    "thumbUrl": "/styles/line/line-51.thumb.webp",
    "displayUrl": "/styles/line/line-51.webp",
    "aspectRatio": 40.2598
  },
  {
    "id": "line-52",
    "category": "line",
    "thumbUrl": "/styles/line/line-52.thumb.webp",
    "displayUrl": "/styles/line/line-52.webp",
    "aspectRatio": 40.2598
  },
  {
    "id": "line-53",
    "category": "line",
    "thumbUrl": "/styles/line/line-53.thumb.webp",
    "displayUrl": "/styles/line/line-53.webp",
    "aspectRatio": 40.2598
  },
  {
    "id": "line-54",
    "category": "line",
    "thumbUrl": "/styles/line/line-54.thumb.webp",
    "displayUrl": "/styles/line/line-54.webp",
    "aspectRatio": 39
  },
  {
    "id": "line-55",
    "category": "line",
    "thumbUrl": "/styles/line/line-55.thumb.webp",
    "displayUrl": "/styles/line/line-55.webp",
    "aspectRatio": 39
  },
  {
    "id": "line-56",
    "category": "line",
    "thumbUrl": "/styles/line/line-56.thumb.webp",
    "displayUrl": "/styles/line/line-56.webp",
    "aspectRatio": 39
  },
  {
    "id": "line-57",
    "category": "line",
    "thumbUrl": "/styles/line/line-57.thumb.webp",
    "displayUrl": "/styles/line/line-57.webp",
    "aspectRatio": 39
  },
  {
    "id": "line-58",
    "category": "line",
    "thumbUrl": "/styles/line/line-58.thumb.webp",
    "displayUrl": "/styles/line/line-58.webp",
    "aspectRatio": 21.3115
  },
  {
    "id": "line-59",
    "category": "line",
    "thumbUrl": "/styles/line/line-59.thumb.webp",
    "displayUrl": "/styles/line/line-59.webp",
    "aspectRatio": 21.3115
  },
  {
    "id": "line-60",
    "category": "line",
    "thumbUrl": "/styles/line/line-60.thumb.webp",
    "displayUrl": "/styles/line/line-60.webp",
    "aspectRatio": 21.3115
  },
  {
    "id": "line-61",
    "category": "line",
    "thumbUrl": "/styles/line/line-61.thumb.webp",
    "displayUrl": "/styles/line/line-61.webp",
    "aspectRatio": 21.3115
  },
  {
    "id": "line-62",
    "category": "line",
    "thumbUrl": "/styles/line/line-62.thumb.webp",
    "displayUrl": "/styles/line/line-62.webp",
    "aspectRatio": 2.6059
  },
  {
    "id": "line-63",
    "category": "line",
    "thumbUrl": "/styles/line/line-63.thumb.webp",
    "displayUrl": "/styles/line/line-63.webp",
    "aspectRatio": 2.6059
  },
  {
    "id": "line-64",
    "category": "line",
    "thumbUrl": "/styles/line/line-64.thumb.webp",
    "displayUrl": "/styles/line/line-64.webp",
    "aspectRatio": 2.6059
  },
  {
    "id": "line-65",
    "category": "line",
    "thumbUrl": "/styles/line/line-65.thumb.webp",
    "displayUrl": "/styles/line/line-65.webp",
    "aspectRatio": 2.6059
  },
  {
    "id": "line-66",
    "category": "line",
    "thumbUrl": "/styles/line/line-66.thumb.webp",
    "displayUrl": "/styles/line/line-66.webp",
    "aspectRatio": 2.6059
  },
  {
    "id": "shape-01",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-01.thumb.webp",
    "displayUrl": "/styles/shape/shape-01.webp",
    "aspectRatio": 1.2829
  },
  {
    "id": "shape-02",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-02.thumb.webp",
    "displayUrl": "/styles/shape/shape-02.webp",
    "aspectRatio": 1.382
  },
  {
    "id": "shape-03",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-03.thumb.webp",
    "displayUrl": "/styles/shape/shape-03.webp",
    "aspectRatio": 1.4706
  },
  {
    "id": "shape-04",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-04.thumb.webp",
    "displayUrl": "/styles/shape/shape-04.webp",
    "aspectRatio": 0.8571
  },
  {
    "id": "shape-05",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-05.thumb.webp",
    "displayUrl": "/styles/shape/shape-05.webp",
    "aspectRatio": 1.32
  },
  {
    "id": "shape-06",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-06.thumb.webp",
    "displayUrl": "/styles/shape/shape-06.webp",
    "aspectRatio": 2.2741
  },
  {
    "id": "shape-07",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-07.thumb.webp",
    "displayUrl": "/styles/shape/shape-07.webp",
    "aspectRatio": 0.7702
  },
  {
    "id": "shape-08",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-08.thumb.webp",
    "displayUrl": "/styles/shape/shape-08.webp",
    "aspectRatio": 1.0357
  },
  {
    "id": "shape-09",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-09.thumb.webp",
    "displayUrl": "/styles/shape/shape-09.webp",
    "aspectRatio": 1.6562
  },
  {
    "id": "shape-10",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-10.thumb.webp",
    "displayUrl": "/styles/shape/shape-10.webp",
    "aspectRatio": 1.9555
  },
  {
    "id": "shape-11",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-11.thumb.webp",
    "displayUrl": "/styles/shape/shape-11.webp",
    "aspectRatio": 2.3989
  },
  {
    "id": "shape-12",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-12.thumb.webp",
    "displayUrl": "/styles/shape/shape-12.webp",
    "aspectRatio": 0.9437
  },
  {
    "id": "shape-13",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-13.thumb.webp",
    "displayUrl": "/styles/shape/shape-13.webp",
    "aspectRatio": 3.5144
  },
  {
    "id": "shape-14",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-14.thumb.webp",
    "displayUrl": "/styles/shape/shape-14.webp",
    "aspectRatio": 1.0403
  },
  {
    "id": "shape-15",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-15.thumb.webp",
    "displayUrl": "/styles/shape/shape-15.webp",
    "aspectRatio": 1.0403
  },
  {
    "id": "shape-16",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-16.thumb.webp",
    "displayUrl": "/styles/shape/shape-16.webp",
    "aspectRatio": 1.0034
  },
  {
    "id": "shape-17",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-17.thumb.webp",
    "displayUrl": "/styles/shape/shape-17.webp",
    "aspectRatio": 1.0215
  },
  {
    "id": "shape-18",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-18.thumb.webp",
    "displayUrl": "/styles/shape/shape-18.webp",
    "aspectRatio": 0.9793
  },
  {
    "id": "shape-19",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-19.thumb.webp",
    "displayUrl": "/styles/shape/shape-19.webp",
    "aspectRatio": 1.0418
  },
  {
    "id": "shape-20",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-20.thumb.webp",
    "displayUrl": "/styles/shape/shape-20.webp",
    "aspectRatio": 1.0418
  },
  {
    "id": "shape-21",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-21.thumb.webp",
    "displayUrl": "/styles/shape/shape-21.webp",
    "aspectRatio": 1.0418
  },
  {
    "id": "shape-22",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-22.thumb.webp",
    "displayUrl": "/styles/shape/shape-22.webp",
    "aspectRatio": 1.0417
  },
  {
    "id": "shape-23",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-23.thumb.webp",
    "displayUrl": "/styles/shape/shape-23.webp",
    "aspectRatio": 1.1763
  },
  {
    "id": "shape-24",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-24.thumb.webp",
    "displayUrl": "/styles/shape/shape-24.webp",
    "aspectRatio": 1.3263
  },
  {
    "id": "shape-25",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-25.thumb.webp",
    "displayUrl": "/styles/shape/shape-25.webp",
    "aspectRatio": 1.7065
  },
  {
    "id": "shape-26",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-26.thumb.webp",
    "displayUrl": "/styles/shape/shape-26.webp",
    "aspectRatio": 1.544
  },
  {
    "id": "shape-27",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-27.thumb.webp",
    "displayUrl": "/styles/shape/shape-27.webp",
    "aspectRatio": 1.553
  },
  {
    "id": "shape-28",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-28.thumb.webp",
    "displayUrl": "/styles/shape/shape-28.webp",
    "aspectRatio": 2.2289
  },
  {
    "id": "shape-29",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-29.thumb.webp",
    "displayUrl": "/styles/shape/shape-29.webp",
    "aspectRatio": 1.5393
  },
  {
    "id": "shape-30",
    "category": "shape",
    "thumbUrl": "/styles/shape/shape-30.thumb.webp",
    "displayUrl": "/styles/shape/shape-30.webp",
    "aspectRatio": 1.5829
  },
  {
    "id": "squiggle-01",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-01.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-01.webp",
    "aspectRatio": 0.6033
  },
  {
    "id": "squiggle-02",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-02.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-02.webp",
    "aspectRatio": 0.6033
  },
  {
    "id": "squiggle-03",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-03.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-03.webp",
    "aspectRatio": 0.6033
  },
  {
    "id": "squiggle-04",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-04.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-04.webp",
    "aspectRatio": 0.6033
  },
  {
    "id": "squiggle-05",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-05.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-05.webp",
    "aspectRatio": 0.6033
  },
  {
    "id": "squiggle-06",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-06.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-06.webp",
    "aspectRatio": 0.9163
  },
  {
    "id": "squiggle-07",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-07.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-07.webp",
    "aspectRatio": 0.9163
  },
  {
    "id": "squiggle-08",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-08.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-08.webp",
    "aspectRatio": 0.9163
  },
  {
    "id": "squiggle-09",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-09.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-09.webp",
    "aspectRatio": 0.9163
  },
  {
    "id": "squiggle-10",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-10.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-10.webp",
    "aspectRatio": 0.9163
  },
  {
    "id": "squiggle-11",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-11.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-11.webp",
    "aspectRatio": 0.9163
  },
  {
    "id": "squiggle-12",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-12.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-12.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-13",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-13.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-13.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-14",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-14.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-14.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-15",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-15.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-15.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-16",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-16.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-16.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-17",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-17.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-17.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-18",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-18.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-18.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-19",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-19.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-19.webp",
    "aspectRatio": 1.5689
  },
  {
    "id": "squiggle-20",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-20.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-20.webp",
    "aspectRatio": 7.1067
  },
  {
    "id": "squiggle-21",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-21.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-21.webp",
    "aspectRatio": 7.1067
  },
  {
    "id": "squiggle-22",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-22.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-22.webp",
    "aspectRatio": 7.1067
  },
  {
    "id": "squiggle-23",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-23.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-23.webp",
    "aspectRatio": 7.1067
  },
  {
    "id": "squiggle-24",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-24.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-24.webp",
    "aspectRatio": 7.1067
  },
  {
    "id": "squiggle-25",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-25.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-25.webp",
    "aspectRatio": 7.1067
  },
  {
    "id": "squiggle-26",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-26.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-26.webp",
    "aspectRatio": 2.8391
  },
  {
    "id": "squiggle-27",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-27.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-27.webp",
    "aspectRatio": 2.8391
  },
  {
    "id": "squiggle-28",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-28.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-28.webp",
    "aspectRatio": 2.8391
  },
  {
    "id": "squiggle-29",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-29.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-29.webp",
    "aspectRatio": 2.8391
  },
  {
    "id": "squiggle-30",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-30.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-30.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-31",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-31.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-31.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-32",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-32.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-32.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-33",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-33.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-33.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-34",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-34.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-34.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-35",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-35.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-35.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-36",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-36.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-36.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-37",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-37.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-37.webp",
    "aspectRatio": 2.4047
  },
  {
    "id": "squiggle-38",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-38.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-38.webp",
    "aspectRatio": 4.7842
  },
  {
    "id": "squiggle-39",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-39.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-39.webp",
    "aspectRatio": 4.7842
  },
  {
    "id": "squiggle-40",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-40.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-40.webp",
    "aspectRatio": 4.7842
  },
  {
    "id": "squiggle-41",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-41.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-41.webp",
    "aspectRatio": 4.7842
  },
  {
    "id": "squiggle-42",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-42.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-42.webp",
    "aspectRatio": 4.7842
  },
  {
    "id": "squiggle-43",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-43.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-43.webp",
    "aspectRatio": 4.7842
  },
  {
    "id": "squiggle-44",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-44.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-44.webp",
    "aspectRatio": 4.7842
  },
  {
    "id": "squiggle-45",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-45.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-45.webp",
    "aspectRatio": 1.3573
  },
  {
    "id": "squiggle-46",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-46.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-46.webp",
    "aspectRatio": 1.3573
  },
  {
    "id": "squiggle-47",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-47.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-47.webp",
    "aspectRatio": 1.3573
  },
  {
    "id": "squiggle-48",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-48.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-48.webp",
    "aspectRatio": 1.3573
  },
  {
    "id": "squiggle-49",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-49.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-49.webp",
    "aspectRatio": 1.3573
  },
  {
    "id": "squiggle-50",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-50.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-50.webp",
    "aspectRatio": 1.3573
  },
  {
    "id": "squiggle-51",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-51.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-51.webp",
    "aspectRatio": 1.3573
  },
  {
    "id": "squiggle-52",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-52.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-52.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-53",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-53.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-53.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-54",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-54.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-54.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-55",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-55.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-55.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-56",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-56.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-56.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-57",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-57.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-57.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-58",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-58.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-58.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-59",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-59.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-59.webp",
    "aspectRatio": 4.4987
  },
  {
    "id": "squiggle-60",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-60.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-60.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-61",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-61.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-61.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-62",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-62.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-62.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-63",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-63.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-63.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-64",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-64.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-64.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-65",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-65.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-65.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-66",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-66.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-66.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-67",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-67.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-67.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-68",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-68.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-68.webp",
    "aspectRatio": 1.0279
  },
  {
    "id": "squiggle-69",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-69.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-69.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-70",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-70.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-70.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-71",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-71.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-71.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-72",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-72.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-72.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-73",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-73.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-73.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-74",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-74.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-74.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-75",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-75.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-75.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-76",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-76.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-76.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-77",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-77.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-77.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-78",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-78.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-78.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-79",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-79.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-79.webp",
    "aspectRatio": 1.3403
  },
  {
    "id": "squiggle-80",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-80.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-80.webp",
    "aspectRatio": 1.0086
  },
  {
    "id": "squiggle-81",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-81.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-81.webp",
    "aspectRatio": 1.0086
  },
  {
    "id": "squiggle-82",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-82.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-82.webp",
    "aspectRatio": 1.0086
  },
  {
    "id": "squiggle-83",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-83.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-83.webp",
    "aspectRatio": 1.0086
  },
  {
    "id": "squiggle-84",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-84.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-84.webp",
    "aspectRatio": 1.0086
  },
  {
    "id": "squiggle-85",
    "category": "squiggle",
    "thumbUrl": "/styles/squiggle/squiggle-85.thumb.webp",
    "displayUrl": "/styles/squiggle/squiggle-85.webp",
    "aspectRatio": 1.0086
  }
];

export const ASSETS_BY_CATEGORY: Record<StyleCategory, StyleAsset[]> =
  STYLE_ASSETS.reduce((acc, a) => {
    (acc[a.category] ??= []).push(a);
    return acc;
  }, {} as Record<StyleCategory, StyleAsset[]>);

export function getStyleAsset(id: string): StyleAsset | undefined {
  return findAsset(STYLE_ASSETS, id);
}

export { findAsset, filterAssets };
