-- Make newsletter_subscribers.email case-insensitive. The original migration
-- 005 created a plain `unique (email)` constraint, which treats Alice@x.com
-- and alice@x.com as distinct. This migration deduplicates any existing rows
-- (keeping the earliest signup per lowered email), normalizes survivors to
-- lowercase, then replaces the constraint with a unique index on lower(email).
-- The client (subscribe() in newsletter-actions.ts) also lowercases before
-- insert; this index is the authoritative server-side guarantee.

-- 1. Dedupe: keep the oldest row per lowered email. Runs before constraint
--    drop so that "oldest per group" is meaningful while constraint is still
--    enforced (no harm if the table is empty).
delete from public.newsletter_subscribers a
using public.newsletter_subscribers b
where lower(a.email) = lower(b.email)
  and a.created_at > b.created_at;

-- 2. Drop the autogenerated unique constraint from migration 005. The default
--    name follows the Postgres pattern <table>_<column>_key.
alter table public.newsletter_subscribers
  drop constraint if exists newsletter_subscribers_email_key;

-- 3. Normalize survivors to lowercase (idempotent).
update public.newsletter_subscribers
  set email = lower(email)
  where email <> lower(email);

-- 4. Enforce case-insensitive uniqueness via a unique expression index.
create unique index if not exists newsletter_subscribers_email_lower_idx
  on public.newsletter_subscribers (lower(email));
